# echo sha256 LEDA 
# echo ---------------------------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/MIT_CEP/sha256/sha256_leda.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/MIT_CEP/sha256/  -e $mero_v2_1/src/ -m  sha256  -seq -scan 1 -lib  LEDA  -v -thr 0.2 -N 10 -T 1 -TS 10000 -wTrojFile -tFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/MIT_CEP/sha256//valid_trojans_1.txt  -seed 0 -tvF 0 -cF 1 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/MIT_CEP/sha256//pre_opt_only_vector_w_nets.txt  -justTroj 0 -justOptCov 1 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -clk  clk  -clkV 0 -woreset -tmaxSrc ECE
# mail -s "sha256_results_10_1" pravin.gaikwad@ufl.edu < /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/MIT_CEP/sha256//results_10_1.txt
# echo ---------------------------------------

echo c2670 LEDA 

# echo ==== flow with new Trojans ====
# echo ----------------1 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 1 -TS 1000 -woTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_1.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 
# echo ----------------2 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 2 -TS 1000 -woTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_1.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 
# echo ----------------3 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 3 -TS 1000 -woTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_1.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 
# echo ----------------4 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 4 -TS 1000 -woTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_1.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 -wTmax 1

# echo ==== flow with prev Trojans ====
# echo ----------------1 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 1 -TS 1000 -wTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_1.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 
# echo ----------------2 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 2 -TS 1000 -wTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_2.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 
# echo ----------------3 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 3 -TS 1000 -wTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_3.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 
# echo ----------------4 trigger Trojan-----------------------
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 4 -TS 1000 -wTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_4.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 -wTmax 1

# flow with Tmax
python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 4 -TS 1000 -woTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_1.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 -wTmax 1

# remaing flow without Tmax
python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 4 -TS 1000 -wTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_4.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 -wTmax 0

#entire flow with Trojan file
# python3 mero.py -f  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/c1908_netlist.v  -d  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/  -e /home/UFAD/pravin.gaikwad/mero_v2_1/src/ -m c1908 -comb -scan 1 -lib LEDA -v -thr 0.5 -N 10 -T 4 -TS 1000 -wTrojFile -tFile /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/valid_trojans_4.txt -seed 0 -tvF 1 -cF 0 -vFlag 0 -vFile  /home/UFAD/pravin.gaikwad/Benchmarks//LEDA/ISCAS85/c1908/pre_opt_only_vector_w_nets.txt -justTroj 0 -justOptCov 0 -postOpt 0 -codeBase $base/mero_cast/ -compareiVeriFlag 1 -tmaxSrc ECE -graphStruct 0 -ndApp -1 -wTmax -1

